### PR TITLE
Update SCB charge values for 2.0/1.5

### PR DESCRIPTION
**Pull request by amarshall**
See [this forum post](https://forums.frontier.co.uk/showthread.php?t=233568) and [derivative post by Kornelius](http://nosuchwebpage.com/index.php?lan=EN&post_id=202).

### CODE REVIEW

**Comment by cmmcleod** [comment]
Thanks for the PR! :)

I've done some investigating and have tweaked those numbers a bit:

https://forums.frontier.co.uk/showthread.php?t=233568&p=3601785&viewfull=1#post3601785

Discussion ongoing. Holding off on merging for now

**Comment by cmmcleod** [comment]
Merged correct data in a separate commit (df88dd9afb1b577baff231096ffef7430ac2d853)

Thanks again for the great starting point! 

Closing

**Comment by amarshall** [comment]
Happy to have helped, looking forward to it being deployed!

**Comment by cmmcleod** [comment]
It's deployed :)

**Comment by amarshall** [comment]
Really? I’m still seeing the old values (and “Version 1.10.4 - 2016-02-10”).

**Comment by cmmcleod** [comment]
Umm.. whooops looks like my deployment failed. Fixed now!

Also, you can access 2.0 Beta at https://coriolis.io

**Pull request closed without merging**
